### ISSUE TITLE
Using ModelController's to handle both models and its views

### ISSUE THREAD

**Issue by roideuniverse** [carrot/recycler-core#1]
Hi, so when we were discussing about it, this idea of List of ModelControllers occured to me. Here is a written description about it.
- How about  we change
  `public abstract class RecyclerCoreAdapter extends RecyclerView.Adapter<RecyclerCoreController>` 
  to
  `public abstract class RecyclerCoreAdapter extends RecyclerView.Adapter<RecyclerCoreViewHolder>`
  and the adapter will have a list of  `private List<RecyclerCoreModelController> mModelControllerList;`
- The `RecyclerCoreModelController` will have methods 
  `RecyclerCoreViewHolder getViewHolder(LayoutInflater inflater, ViewGroup parent, Activity activity)` and `public abstract RecyclerCoreModel getModel();`
- And we will have `RecyclerCoreViewHolder<ModelController extends RecyclerCoreModelController> extends RecyclerView.ViewHolder`

How does that look?

**Comment by BrandonRomano** [comment]
While I think that what you described resolves the weird model inflating the view/controller oddity, I have concerns that using the library will become a little more tedious from an end user perspective.

If you could actually implement this and show me how it would be used that would be the way to go with this one I think.

**Comment by roideuniverse** [comment]
We did an internal discussion and it does not look a good way - it makes the job of the developer more tedious - as they would have to create one more extra controller and then pass the model and to the controller, so closing.
